# Generated by Django 6.0.6 on 2026-07-12 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_alter_transaction_account_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date(2026, 7, 12), verbose_name='Transaction Date'),
        ),
    ]
